permalink: /:title
markdown: redcarpet
pygments: true


title: Dustin Ewers
tagline: Software Developer | Writer | Philomath
author:
  name: Dustin Ewers
  email: dustin.ewers@gmail.com
  github: DustinEwers
  twitter: DustinJEwers
  linkedin: dustinewers

rss_path: /rss.xml
prod_url: "http://dustinewers.github.io"




